stages:
  - lint

lint:
  stage: lint
  image: gradle:7.5.1-jdk17-focal
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    # lint and compile projects
    - gradle build --console=verbose --no-daemon
  cache:
    paths:
      - .gradle
